name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.24.x]
        full-tests: [false]
        include:
          - go-version: 1.24.x
            full-tests: true

    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3' # TODO: fix matrix
          cache: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Linting
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          working-directory: .
          version: latest
          verify: true
          args: --config=.golangci.yml

      - name: Testing
        continue-on-error: ${{ matrix.go-version == 'tip' }}
        run: |
          go version
          export GORACE="halt_on_error=1"
          go test -v -race ./...
